Si vous avez l'erreur suivante :

```bash
./python/cat.py /r1/r2/f2
Traceback (most recent call last):
  File "./python/cat.py", line 37, in <module>
    fs = open ("td2.MinixFS", "rb")
```

Remplacez "td2.MinixFS" par "tp6.MinixFS"
